name: Build PDFs

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build LaTeX (exclude docsiamart.tex)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ex_article.tex
            ex_supplement.tex
          latexmk_shell_escape: false
          extra_system_packages: ""   # add biber or others if your .tex needs them
          continue_on_error: false

      - name: Collect PDFs
        run: |
          mkdir -p pdf
          shopt -s nullglob
          mv *.pdf pdf/

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: pdf/*.pdf

      - name: Commit PDFs back
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: build PDFs"
          file_pattern: "pdf/*.pdf"
